const reduce=matchMedia('(prefers-reduced-motion: reduce)');let motion=!reduce.matches;
try{if(localStorage.getItem('sst-motion')==='off')motion=false}catch{}
const motionButton=document.querySelector('#motion-toggle');function syncMotion(){document.documentElement.classList.toggle('motion-paused',!motion);if(motionButton){motionButton.textContent=motion?'Анимация: включена':'Анимация: выключена';motionButton.setAttribute('aria-pressed',String(motion));}document.dispatchEvent(new CustomEvent('sst:motion',{detail:motion}));document.querySelectorAll('video[data-autoplay]').forEach(v=>{if(motion)v.play().catch(()=>{});else v.pause()});}
motionButton?.addEventListener('click',()=>{motion=!motion;try{localStorage.setItem('sst-motion',motion?'on':'off')}catch{}syncMotion()});reduce.addEventListener('change',()=>{motion=!reduce.matches;syncMotion()});syncMotion();
const menu=document.querySelector('#site-menu'),toggle=document.querySelector('.menu-toggle');toggle?.addEventListener('click',()=>{menu.showModal();toggle.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'});function closeMenu(){menu.close();toggle.setAttribute('aria-expanded','false');document.body.style.overflow='';toggle.focus()}document.querySelector('.menu-close')?.addEventListener('click',closeMenu);menu?.addEventListener('cancel',e=>{e.preventDefault();closeMenu()});menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.close();document.body.style.overflow=''}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.intro-layout,.section-heading,.project-entry,.section-label,.stats-grid>div,.company-conclusion,.brief-grid,.contact-columns').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
const storyObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('is-active',e.isIntersecting)),{rootMargin:'-20% 0px -20% 0px'});document.querySelectorAll('.story-step').forEach(x=>storyObserver.observe(x));
let pending=false;function scrollScene(){const total=document.documentElement.scrollHeight-innerHeight;document.querySelector('.scroll-progress').style.width=(total>0?scrollY/total*100:0)+'%';if(!motion)return;const hero=document.querySelector('.cinema-hero');if(hero){const r=hero.getBoundingClientRect();if(r.bottom>0){const progress=Math.min(1,Math.max(0,-r.top/r.height));hero.querySelector('.hero-media').style.transform=`translateY(${progress*130}px) scale(${1+progress*.09})`;hero.querySelectorAll('.hero-line').forEach((x,i)=>x.style.transform=`translateX(${progress*(i?-60:60)}px)`);}}document.querySelectorAll('.wide-image img').forEach(el=>{const r=el.parentElement.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)el.style.transform=`translateY(${(innerHeight/2-r.top-r.height/2)*.06}px)`});}
window.addEventListener('scroll',()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{scrollScene();pending=false})},{passive:true});scrollScene();
const stage=document.querySelector('#logo-stage');if(stage){const loadObserver=new IntersectionObserver(async entries=>{if(!entries[0].isIntersecting)return;loadObserver.disconnect();try{const {initLogo}=await import('./logo.js');await initLogo(stage,()=>motion);}catch{stage.setAttribute('aria-label','Фирменный знак ССТ');document.querySelector('.model-caption').textContent='СПЕЦСТРОЙТЕХНОЛОГИИ';}},{rootMargin:'500px'});loadObserver.observe(stage);}
document.querySelectorAll('.transform-card').forEach(card=>{const button=card.querySelector('.card-toggle'),reverse=card.querySelector('.card-reverse');function open(value){card.classList.toggle('is-open',value);button.setAttribute('aria-expanded',String(value));reverse.inert=!value;if(!value&&reverse.contains(document.activeElement))button.focus();}const closeButton=document.createElement('button');closeButton.type='button';closeButton.className='card-close';closeButton.textContent='Закрыть ×';closeButton.onclick=()=>open(false);reverse.append(closeButton);reverse.inert=true;button.addEventListener('click',e=>{e.stopPropagation();const next=!card.classList.contains('is-open');open(next);if(next)closeButton.focus()});card.addEventListener('click',e=>{if(card.classList.contains('is-open')&&!e.target.closest('a,button'))open(false)});card.addEventListener('keydown',e=>{if(e.key==='Escape'){open(false);button.focus()}});card.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&motion)open(true)});card.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse'&&!card.contains(document.activeElement))open(false)});});
document.querySelectorAll('.button,.circle-link').forEach(el=>{el.addEventListener('pointermove',e=>{if(!motion||e.pointerType==='touch')return;const r=el.getBoundingClientRect();el.style.translate=`${(e.clientX-r.left-r.width/2)*.035}px ${(e.clientY-r.top-r.height/2)*.05}px`});el.addEventListener('pointerleave',()=>el.style.translate='0 0')});
const cursor=document.querySelector('#hover-cursor');document.querySelectorAll('[data-cursor]').forEach(el=>{el.addEventListener('pointermove',e=>{if(!motion||e.pointerType!=='mouse'||innerWidth<900)return;cursor.style.display='flex';cursor.style.transform=`translate(${e.clientX+14}px,${e.clientY+14}px)`;cursor.textContent=el.dataset.cursor});el.addEventListener('pointerleave',()=>cursor.style.display='none')});
document.querySelector('#collection-search')?.addEventListener('input',e=>{const query=e.target.value.toLocaleLowerCase('ru');document.querySelectorAll('.project-entry,.service-card,.vacancy-list>a,.equipment-rail article').forEach(el=>el.hidden=!el.textContent.toLocaleLowerCase('ru').includes(query))});
const form=document.querySelector('#project-form');if(form){let files=[];const input=form.querySelector('[type=file]'),drop=document.querySelector('#file-drop'),list=document.querySelector('#selected-files'),status=document.querySelector('#form-status');const safeText=(el,t)=>el.textContent=t;
function renderFiles(){list.replaceChildren();files.forEach((f,i)=>{const li=document.createElement('li'),span=document.createElement('span'),button=document.createElement('button');span.textContent=f.name+' · '+(f.size/1024/1024).toFixed(1)+' МБ';button.type='button';button.textContent='×';button.setAttribute('aria-label','Удалить '+f.name);button.onclick=()=>{files.splice(i,1);renderFiles()};li.append(span,button);list.append(li)});}
function addFiles(next){if(files.length+next.length>5){status.textContent='Можно приложить до 5 файлов.';return;}if(next.some(f=>f.size>8*1024*1024||! /\.(pdf|docx?|xlsx?|jpe?g|png|webp)$/i.test(f.name))){status.textContent='Проверьте формат файла и размер: не более 8 МБ.';return;}files.push(...next);status.textContent='';renderFiles();}
input.addEventListener('change',()=>{addFiles([...input.files]);input.value=''});for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.add('drag-over')});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('drag-over');if(event==='drop')addFiles([...e.dataTransfer.files])});
form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);if(!data.get('phone')&&!data.get('email')){status.textContent='Укажите телефон или email для ответа.';form.elements.phone.focus();return;}data.delete('files');files.forEach(f=>data.append('files',f));data.set('source',location.pathname);const button=form.querySelector('[type=submit]');button.disabled=true;status.className='';status.textContent='Сохраняем обращение…';try{const response=await fetch('/api/leads',{method:'POST',body:data}),result=await response.json();if(!response.ok)throw Error(result.error||'Не удалось отправить обращение');status.className='success';status.textContent='Обращение получено. Материалы сохранены и доступны команде ССТ. Спасибо за ваш проект.';form.reset();files=[];renderFiles();}catch(error){status.textContent=error.message+' Вы также можете связаться по телефону или email.';}finally{button.disabled=false;}});}
