import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.DATA_DIR=await mkdtemp(join(tmpdir(),'sst-test-'));
process.env.APP_ORIGIN='http://localhost:8797';
delete process.env.SMTP_HOST;
const {db,id,now}=await import('../src/db.mjs');
const {hashPassword}=await import('../src/security.mjs');
const {start}=await import('../src/server.mjs');
const {validateFile}=await import('../src/media.mjs');
const server=start(0);await new Promise(r=>server.listening?r():server.once('listening',r));
const url='http://127.0.0.1:'+server.address().port;
const password='test-only-random-'+id();
for(const role of ['admin','editor'])db.prepare('INSERT INTO users(id,email,name,role,password,created_at) VALUES(?,?,?,?,?,?)').run(id(),role+'@example.test',role,role,await hashPassword(password),now());
async function request(path,{method='GET',body,cookie,csrf,origin=process.env.APP_ORIGIN,raw}={}){return fetch(url+path,{method,headers:{Origin:origin,...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{}),...(body?{'Content-Type':'application/json'}:{})},body:raw|| (body?JSON.stringify(body):undefined)});}
async function login(role){const r=await request('/api/login',{method:'POST',body:{email:role+'@example.test',password}});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);const cookie=r.headers.get('set-cookie').split(';')[0];const s=await request('/api/admin/session',{cookie});const d=await s.json();return{cookie,csrf:d.csrf};}
test('Public pages, private CMS, editorial publishing and real leads',async t=>{
 const admin=await login('admin'),editor=await login('editor');
 await t.test('public routes and no secrets exposed',async()=>{for(const path of ['/','/company','/contacts','/privacy','/capabilities','/projects','/news','/suppliers','/admin','/sitemap.xml','/robots.txt','/logo.js'])assert.equal((await request(path)).status,200,path);for(const path of ['/.env','/data/sst.sqlite','/src/server.mjs','/unknown'])assert.equal((await request(path)).status,404,path);assert.equal((await request('/api/admin/leads')).status,401);assert.equal((await request('/api/admin/leads',editor)).status,403);assert.equal((await request('/api/admin/users',editor)).status,403);});
 await t.test('origin and CSRF enforced',async()=>{assert.equal((await request('/api/admin/settings',{...admin,method:'PUT',csrf:'bad',body:{brand:'test'}})).status,403);assert.equal((await request('/api/admin/settings',{...admin,method:'PUT',origin:'https://evil.example',body:{brand:'test'}})).status,403);assert.equal((await request('/api/admin/settings',{...editor,method:'PUT',body:{brand:'test'}})).status,403);});
 let item;
 await t.test('drafts hidden, unsaved private preview, publish and escaping',async()=>{const draft={title:'Тест <script>alert(1)</script>',slug:'qa-project',status:'draft',body:'Проверка публикации',image:'/assets/construction.webp',gallery:[]};let r=await request('/api/admin/content/projects',{...editor,method:'POST',body:draft});assert.equal(r.status,200);item=await r.json();assert.equal((await request('/projects/qa-project')).status,404);r=await request('/api/admin/preview',{...editor,method:'POST',body:{...item,kind:'projects'}});assert.equal(r.status,200);const p=await r.json();assert.equal((await request(p.url)).status,401);assert.equal((await request(p.url,editor)).status,200);r=await request('/api/admin/content/projects/'+item.id,{...editor,method:'PUT',body:{...item,status:'published'}});assert.equal(r.status,200);const next=await r.json();assert.equal((await request('/api/admin/content/projects/'+item.id,{...editor,method:'PUT',body:{...item,updated_at:'old'}})).status,409);item=next;const html=await(await request('/projects/qa-project')).text();assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>alert/);assert.equal((await request('/projects')).status,200);});
 await t.test('image optimization, referenced media and invalid file guards',async()=>{const sharp=(await import('sharp')).default;const image=await sharp({create:{width:30,height:20,channels:3,background:'#1b2943'}}).png().toBuffer();let r=await fetch(url+'/api/admin/media',{method:'POST',headers:{Origin:process.env.APP_ORIGIN,Cookie:admin.cookie,'X-CSRF-Token':admin.csrf,'X-File-Name':'qa.png'},body:image});assert.equal(r.status,201);const m=await r.json();assert.equal(Object.keys(m.variants).length,3);assert.equal((await request(m.url)).status,200);r=await request('/api/admin/content/projects/'+item.id,{...admin,method:'PUT',body:{...item,image:m.url}});item=await r.json();assert.equal((await request('/api/admin/media/'+m.id,{...admin,method:'DELETE'})).status,409);assert.throws(()=>validateFile(Buffer.from('a'),'bad.docx'),e=>e.status===400);});
 await t.test('lead persisted, file private, roles separated',async()=>{const form=new FormData();form.set('name','QA');form.set('email','qa@example.test');form.set('message','Проверка формы');form.set('consent','yes');form.append('files',new Blob(['%PDF-1.4\nQA']), 'brief.pdf');const r=await request('/api/leads',{method:'POST',raw:form});assert.equal(r.status,201);const rows=await(await request('/api/admin/leads',admin)).json();assert.equal(rows.length,1);assert.equal(rows[0].data.message,'Проверка формы');const file='/api/admin/files/'+rows[0].files[0].id;assert.equal((await request(file)).status,401);assert.equal((await request(file,editor)).status,403);assert.equal((await request(file,admin)).status,200);assert.equal((await request('/api/admin/leads/'+rows[0].id,{...admin,method:'PUT',body:{status:'working',notes:'Проверено'}})).status,200);});
 await t.test('archive removes public content',async()=>{assert.equal((await request('/api/admin/content/projects/'+item.id,{...admin,method:'DELETE'})).status,200);assert.equal((await request('/projects/qa-project')).status,404);});
});
test.after(async()=>{await new Promise(r=>server.close(r));db.close();await rm(process.env.DATA_DIR,{recursive:true,force:true});});
