export const sections = {
 projects:{label:'Проекты',singular:'Проект',route:'projects'},services:{label:'Компетенции',singular:'Компетенция',route:'competencies'},technologies:{label:'Технологии',singular:'Технология',route:'technologies'},equipment:{label:'Техника',singular:'Техника',route:'equipment'},vacancies:{label:'Карьера',singular:'Вакансия',route:'career'},news:{label:'Новости',singular:'Новость',route:'news'},documents:{label:'Документы',singular:'Документ',route:'documents'},partners:{label:'Партнёрам',singular:'Материал',route:'partners'},customers:{label:'Заказчикам',singular:'Материал',route:'customers'},procurement:{label:'Закупки',singular:'Закупка',route:'procurement'},stats:{label:'Показатели',singular:'Показатель',route:null}
};
export const defaults={
 brand:'СПЕЦСТРОЙТЕХНОЛОГИИ',legalName:'ООО «Спецстройтехнологии»',phone:'+7 (965) 010-61-45',email:'info@spstech.ru',address:'Ленинградская область, с. Русско-Высоцкое, ул. Промышленная, зд. 1, офис 35',legalAddress:'188516, Ленинградская область, Ломоносовский район, с. Русско-Высоцкое, ул. Промышленная, зд. 1, офис 35',inn:'7816700000',kpp:'472501001',ogrn:'1197847195127',mapUrl:'https://yandex.ru/maps/?text=Ленинградская%20область%20Русско-Высоцкое%20Промышленная%201',hours:'',socialLinks:[],
 heroTitle:'Сложное.\nВ простом.',heroSubtitle:'Строительство начинается с идеи.\nНадёжность — с внимания к деталям.',heroImage:'/assets/construction.webp',heroVideo:'',heroCaption:'Визуализация фирменного стиля ССТ',cta:'Обсудить проект',companyText:'«Спецстрой Технологии» — строительная компания. Наше имя соединяет специализацию, строительство и технологии. А наш знак выражает главный принцип: сложное в простом.',
 seoTitle:'Спецстройтехнологии — Сложное. В простом.',seoDescription:'Спецстройтехнологии. Точность. Структура. Результат. Обсудите ваш строительный проект с нашей командой.',ogImage:'',logo:'/assets/emblem.svg',favicon:'/assets/emblem.svg',
 homeSections:['intro','form','principles','projects','services','stats','news'],hiddenSections:[],navigationOrder:['company','projects','services','technologies','equipment','vacancies','news','documents','partners','customers','procurement','contacts'],hiddenNavigation:[],navigationLabels:{},retentionDays:365
};
export const principles=[{title:'Понимать задачу',subtitle:'Отправная точка',text:'Назначение объекта, условия площадки и ожидания заказчика — отправная точка любого строительного проекта.'},{title:'Видеть связи',subtitle:'Единая система',text:'Технологии, материалы и последовательность работ должны складываться в единую систему.'},{title:'Держать фокус',subtitle:'Точность в деталях',text:'Внимание к узлам, стыкам и деталям определяет качество целого. Точность имеет значение на каждом этапе.'}];
export const faq=[['Что подготовить к первому разговору?','Кратко опишите объект, его расположение и текущую стадию. Если уже есть чертежи, техническое задание или фотографии площадки, приложите их к обращению.'],['Можно обратиться без готового проекта?','Начать обсуждение можно с идеи. Укажите назначение объекта, примерные размеры и желаемый результат — это поможет сформулировать следующие вопросы.'],['Какие данные нужны для оценки?','Стоимость и сроки зависят от объёма работ, технических решений, площадки и исходной документации. Чем подробнее вводные, тем предметнее разговор об оценке проекта.'],['Куда направить документацию?','Прикрепите материалы к форме обращения или отправьте их на корпоративную почту. Укажите название проекта, контактное лицо и удобный способ связи.']];
