import sharp from 'sharp';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {db,dataDir,id,now} from './db.mjs';
import {fail} from './security.mjs';
const types={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp','.pdf':'application/pdf','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xls':'application/vnd.ms-excel','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.mp4':'video/mp4','.webm':'video/webm'};
export function validateFile(bytes,name,{video=false}={}){const ext=extname(name).toLowerCase(),mime=types[ext];if(!mime||(!video&&mime.startsWith('video/')))fail('Этот формат файла не поддерживается');if(!bytes.length||bytes.length>(video?30:8)*1024*1024)fail('Превышен допустимый размер файла',413);if(bytes.length<4)fail('Файл повреждён');const h=bytes.subarray(0,16);let ok=false;if(ext==='.jpg'||ext==='.jpeg')ok=h[0]===255&&h[1]===216&&h[2]===255;else if(ext==='.png')ok=h.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex'));else if(ext==='.webp')ok=h.toString('ascii',0,4)==='RIFF'&&h.toString('ascii',8,12)==='WEBP';else if(ext==='.pdf')ok=h.toString('ascii',0,5)==='%PDF-';else if(['.docx','.xlsx'].includes(ext))ok=h.readUInt32LE(0)===0x04034b50;else if(['.doc','.xls'].includes(ext))ok=h.subarray(0,8).equals(Buffer.from('d0cf11e0a1b11ae1','hex'));else if(ext==='.mp4')ok=h.toString('ascii',4,8)==='ftyp';else if(ext==='.webm')ok=h.readUInt32BE(0)===0x1a45dfa3;if(!ok)fail('Содержимое файла не соответствует его расширению');return {ext,mime};}
export async function saveMedia(bytes,name){const{ext,mime}=validateFile(bytes,name,{video:true}),uid=id(),dir=resolve(dataDir,'media');await mkdir(dir,{recursive:true});let path=uid+ext,variants={};if(mime.startsWith('image/')){let pipeline;try{pipeline=sharp(bytes,{limitInputPixels:40000000}).rotate();await pipeline.metadata();}catch{fail('Не удалось прочитать изображение');}for(const width of [640,1280,2200]){const file=`${uid}-${width}.webp`;await pipeline.clone().resize({width,withoutEnlargement:true}).webp({quality:84}).toFile(resolve(dir,file));variants[width]='/media/'+file;}path=uid+ext;await writeFile(resolve(dir,path),bytes);}else await writeFile(resolve(dir,path),bytes);db.prepare('INSERT INTO media(id,name,mime,size,path,variants,created_at) VALUES(?,?,?,?,?,?,?)').run(uid,name.slice(0,200),mime,bytes.length,path,JSON.stringify(variants),now());return {id:uid,name,mime,size:bytes.length,url:variants[2200]||'/media/'+path,variants};}
export function mediaRow(row){return {...row,variants:JSON.parse(row.variants),url:JSON.parse(row.variants)[2200]||'/media/'+row.path};}
export async function saveLeadFile(leadId,bytes,name){const{ext,mime}=validateFile(bytes,name);const uid=id(),path=uid+ext,dir=resolve(dataDir,'private');await mkdir(dir,{recursive:true});await writeFile(resolve(dir,path),bytes,{mode:0o600});db.prepare('INSERT INTO lead_files VALUES(?,?,?,?,?,?)').run(uid,leadId,name.slice(0,200),mime,bytes.length,path);return uid;}
export const mimeFor=path=>types[extname(path).toLowerCase()]||'application/octet-stream';
