import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {db,dataDir,id,now,list,unpack,settings,audit} from './db.mjs';
import {sections,defaults} from './content.mjs';
import {origin,sameOrigin,session,requireUser,cookie,createSession,verifyPassword,hashPassword,limit,fail} from './security.mjs';
import {saveMedia,mediaRow,saveLeadFile,validateFile,mimeFor} from './media.mjs';
import {enqueue,deliverNotifications} from './notifications.mjs';
import {renderPage,renderAdmin,notFound} from './render.mjs';
const publicDir=resolve('dist');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2','.txt':'text/plain; charset=utf-8'};
async function bytes(req,max=1024*1024){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>max)fail('Слишком большой запрос',413);chunks.push(chunk);}return Buffer.concat(chunks);}
async function json(req){if(!req.headers['content-type']?.startsWith('application/json'))fail('Ожидается JSON',415);try{return JSON.parse((await bytes(req)).toString());}catch(e){if(e.status)throw e;fail('Некорректный JSON');}}
function reply(res,status,data,headers={}){res.writeHead(status,{'Content-Type':typeof data==='string'?'text/html; charset=utf-8':'application/json; charset=utf-8',...headers});res.end(typeof data==='string'?data:JSON.stringify(data));}
const text=(x,max=20000)=>typeof x==='string'?x.trim().slice(0,max):'';
const safeAsset=x=>typeof x==='string'&&(/^\/(assets|media)\/[a-zA-Z0-9._/-]+$/.test(x))&&!x.includes('..');
function record(data,kind){if(!sections[kind])fail('Неизвестный раздел',404);if(!data||typeof data!=='object'||Array.isArray(data))fail('Некорректные данные');const title=text(data.title,200),slug=text(data.slug,100);if(!title)fail('Введите название');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))fail('Slug: латинские буквы, цифры и дефис');if(!['draft','published','archived'].includes(data.status))fail('Некорректный статус');const allowed=['excerpt','body','region','location','year','objectType','work','specifications','video','seoTitle','seoDescription','date','city','employment','requirements','conditions','contact','category','manufacturer','model','value','unit','caption','latitude','longitude','projectStatus'];const out={};for(const key of allowed)out[key]=text(data[key],key==='body'?50000:10000);for(const key of ['image','document']){out[key]=text(data[key],400);if(out[key]&&!safeAsset(out[key]))fail('Выберите файл из медиатеки');}if(out.video&&!safeAsset(out.video))fail('Выберите видео из медиатеки');for(const [key,max] of [['latitude',85],['longitude',180]])if(out[key]&&(!Number.isFinite(Number(out[key]))||Math.abs(Number(out[key]))>max))fail('Некорректные координаты объекта');out.gallery=Array.isArray(data.gallery)?data.gallery.filter(safeAsset).slice(0,40):[];out.featured=data.featured===true;out.closed=data.closed===true;if(data.status==='published'&&!out.body&&!out.value&&!out.document)fail('Перед публикацией добавьте описание, показатель или документ');if(['projects','news'].includes(kind)&&data.status==='published'&&!out.image)fail('Перед публикацией добавьте обложку');return {title,slug,status:data.status,position:Math.max(-10000,Math.min(10000,Number(data.position)||0)),data:JSON.stringify(out)};}
function updateSettings(data){const current=settings();for(const key of Object.keys(defaults)){if(!(key in data))continue;const val=data[key];if(['homeSections','hiddenSections','navigationOrder','hiddenNavigation'].includes(key)){const permitted=key.includes('avigation')?['company','contacts',...Object.keys(sections)]:defaults.homeSections;if(!Array.isArray(val)||val.some(x=>!permitted.includes(x))||new Set(val).size!==val.length)fail('Некорректный порядок разделов');current[key]=val;}else if(key==='navigationLabels'){if(!val||typeof val!=='object'||Array.isArray(val))fail('Некорректные подписи меню');current[key]=Object.fromEntries(Object.entries(val).filter(([k])=>['company','contacts',...Object.keys(sections)].includes(k)).map(([k,v])=>[k,text(v,50)]));}else if(key==='socialLinks'){if(!Array.isArray(val))fail('Некорректные ссылки');current[key]=val.slice(0,8).map(x=>{if(!/^https:\/\//.test(x.url||''))fail('Для ссылки требуется HTTPS');return{label:text(x.label,40),url:text(x.url,500)};});}else if(key==='retentionDays'){current[key]=Math.max(1,Math.min(3650,Number(val)||365));}else{current[key]=text(val,10000);if(['heroImage','heroVideo','ogImage','logo','favicon'].includes(key)&&val&&!safeAsset(val))fail('Выберите ресурс из медиатеки');if(key==='mapUrl'&&val&&!/^https:\/\//.test(val))fail('Ссылка карты должна начинаться с HTTPS');if(key==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val))fail('Проверьте email');}}
 db.exec('BEGIN');try{for(const[k,v]of Object.entries(current))db.prepare('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,JSON.stringify(v));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return current;
}
async function serveFile(res,req,path,type,attachment){const file=await stat(path).catch(()=>null);if(!file?.isFile())fail('Файл не найден',404);const headers={'Content-Type':type,'Content-Length':file.size,'Cache-Control':attachment?'private, no-store':'public, max-age=3600'};if(attachment)headers['Content-Disposition']="attachment; filename*=UTF-8''"+encodeURIComponent(attachment);res.writeHead(200,headers);if(req.method==='HEAD')res.end();else res.end(await readFile(path));}
export async function handler(req,res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; media-src 'self' blob:; connect-src 'self'; frame-src https://www.google.com https://maps.google.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'");if(origin().startsWith('https:'))res.setHeader('Strict-Transport-Security','max-age=31536000');
 try{const url=new URL(req.url,origin()),path=decodeURIComponent(url.pathname),method=req.method;if(path.startsWith('/api/')||path.startsWith('/admin'))res.setHeader('Cache-Control','no-store');
 if(path==='/health')return reply(res,200,{ok:true});
 if(path==='/api/login'&&method==='POST'){sameOrigin(req);limit('login-ip:'+req.socket.remoteAddress,30,900000);const data=await json(req),email=text(data.email,200).toLowerCase();limit('login:'+email,8,900000);const u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(email);const good=await verifyPassword(text(data.password,256),u?.password||'0'.repeat(32)+':'+'0'.repeat(128));if(!good||!u)fail('Неверный email или пароль',401);const s=createSession(u);return reply(res,200,{ok:true},{'Set-Cookie':cookie(s.token)});}
 if(path==='/api/logout'&&method==='POST'){const u=requireUser(req);db.prepare('DELETE FROM sessions WHERE token=?').run(u.token);return reply(res,200,{ok:true},{'Set-Cookie':cookie('',0)});}
 if(path==='/api/admin/session'){const u=requireUser(req);return reply(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role},csrf:u.csrf});}
 if(path==='/api/leads'&&method==='POST'){sameOrigin(req);limit('lead:'+req.socket.remoteAddress,5,3600000);const buf=await bytes(req,24*1024*1024);let form;try{form=await new Request(origin()+'/api/leads',{method:'POST',headers:{'content-type':req.headers['content-type']||''},body:buf}).formData();}catch{fail('Не удалось прочитать форму');}if(form.get('website'))return reply(res,200,{ok:true});const data={};for(const key of ['name','company','phone','email','projectType','message','source'])data[key]=text(form.get(key),key==='message'?10000:500);if(!data.name||!data.message||(!data.phone&&!data.email))fail('Укажите имя, способ связи и описание проекта');if(data.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email))fail('Проверьте email');if(form.get('consent')!=='yes')fail('Нужно согласие на обработку обращения');data.consentAt=now();data.policyVersion='2026-09-17';const attachments=form.getAll('files').filter(x=>typeof x!=='string'&&x.size);if(attachments.length>5)fail('Можно приложить не более 5 файлов');const files=[];for(const f of attachments){const content=Buffer.from(await f.arrayBuffer());validateFile(content,f.name);files.push({name:f.name,content});}const uid=id();db.prepare('INSERT INTO leads(id,data,created_at,updated_at) VALUES(?,?,?,?)').run(uid,JSON.stringify(data),now(),now());try{for(const f of files)await saveLeadFile(uid,f.content,f.name);}catch(e){db.prepare('DELETE FROM leads WHERE id=?').run(uid);throw e;}enqueue(uid);return reply(res,201,{ok:true,id:uid});}
 if(path.startsWith('/api/admin/')){const u=requireUser(req);const parts=path.split('/').filter(Boolean),resource=parts[2];
 if(resource==='dashboard'&&method==='GET'){const counts={};for(const kind of Object.keys(sections))counts[kind]=db.prepare("SELECT COUNT(*) AS n FROM content WHERE kind=? AND status='published'").get(kind).n;return reply(res,200,{counts,leads:u.role==='admin'?db.prepare("SELECT COUNT(*) AS n FROM leads WHERE status='new'").get().n:null,recent:db.prepare('SELECT id,kind,title,status,updated_at FROM content ORDER BY updated_at DESC LIMIT 8').all(),mailConfigured:!!process.env.SMTP_HOST,notificationFailures:u.role==='admin'?db.prepare("SELECT COUNT(*) AS n FROM notifications WHERE attempts>=5 AND status='pending'").get().n:null});}
 if(resource==='content'){const kind=parts[3];if(!sections[kind])fail('Раздел не найден',404);if(method==='GET')return reply(res,200,list(kind,true));if(['POST','PUT'].includes(method)){const incoming=await json(req),r=record(incoming,kind),uid=parts[4]||id(),old=parts[4]?db.prepare('SELECT * FROM content WHERE id=? AND kind=?').get(uid,kind):null;if(parts[4]&&!old)fail('Материал не найден',404);if(old&&incoming.updated_at!==old.updated_at)fail('Материал уже изменён. Обновите редактор, чтобы не затереть изменения.',409);try{if(old)db.prepare('UPDATE content SET title=?,slug=?,status=?,position=?,data=?,updated_at=? WHERE id=?').run(r.title,r.slug,r.status,r.position,r.data,now(),uid);else db.prepare('INSERT INTO content VALUES(?,?,?,?,?,?,?,?,?)').run(uid,kind,r.slug,r.title,r.status,r.position,r.data,now(),now());}catch(e){if(e.message.includes('UNIQUE'))fail('Этот slug уже занят',409);throw e;}audit(u,(old?'Изменён':'Создан')+' материал: '+r.title,uid);return reply(res,200,unpack(db.prepare('SELECT * FROM content WHERE id=?').get(uid)));}if(method==='DELETE'){const old=db.prepare('SELECT * FROM content WHERE id=? AND kind=?').get(parts[4],kind);if(!old)fail('Материал не найден',404);db.prepare("UPDATE content SET status='archived',updated_at=? WHERE id=?").run(now(),old.id);audit(u,'Архивирован материал: '+old.title,old.id);return reply(res,200,{ok:true});}}
 if(resource==='preview'&&method==='POST'){const incoming=await json(req),r=record({...incoming,status:'draft'},incoming.kind),uid=id(),item={...JSON.parse(r.data),id:incoming.id||uid,kind:incoming.kind,title:r.title,slug:r.slug,status:'draft'};db.prepare('DELETE FROM previews WHERE expires_at<?').run(Date.now());db.prepare('INSERT INTO previews VALUES(?,?,?,?)').run(uid,u.id,JSON.stringify(item),Date.now()+3600000);return reply(res,200,{url:'/admin/preview?token='+uid});}
 if(resource==='settings'){requireUser(req,true);if(method==='GET')return reply(res,200,settings());if(method==='PUT'){const data=updateSettings(await json(req));audit(u,'Изменены настройки сайта');return reply(res,200,data);}}
 if(resource==='media'){if(method==='GET')return reply(res,200,db.prepare('SELECT * FROM media WHERE archived=0 ORDER BY created_at DESC').all().map(row=>{const m=mediaRow(row);return{...m,uses:db.prepare('SELECT title FROM content WHERE data LIKE ?').all('%'+row.id+'%').map(x=>x.title),inSettings:db.prepare('SELECT key FROM settings WHERE value LIKE ?').all('%'+row.id+'%').map(x=>x.key)};}));if(method==='POST'){const name=decodeURIComponent(req.headers['x-file-name']||'file');const result=await saveMedia(await bytes(req,30*1024*1024),name);audit(u,'Загружен файл: '+name,result.id);return reply(res,201,result);}if(method==='DELETE'){const uid=parts[3];if(db.prepare('SELECT id FROM content WHERE data LIKE ?').get('%'+uid+'%')||db.prepare('SELECT key FROM settings WHERE value LIKE ?').get('%'+uid+'%'))fail('Файл используется. Сначала удалите ссылки на него.',409);db.prepare('UPDATE media SET archived=1 WHERE id=?').run(uid);audit(u,'Файл перемещён в архив',uid);return reply(res,200,{ok:true});}}
 if(resource==='leads'){requireUser(req,true);if(method==='GET'){const rows=db.prepare('SELECT * FROM leads ORDER BY created_at DESC').all().map(r=>({...r,data:JSON.parse(r.data),files:db.prepare('SELECT id,name,size,mime FROM lead_files WHERE lead_id=?').all(r.id)}));return reply(res,200,rows);}if(method==='PUT'){const data=await json(req);if(!['new','working','done','archived'].includes(data.status))fail('Некорректный статус');db.prepare('UPDATE leads SET status=?,notes=?,updated_at=? WHERE id=?').run(data.status,text(data.notes),now(),parts[3]);audit(u,'Изменена заявка',parts[3]);return reply(res,200,{ok:true});}}
 if(resource==='files'&&method==='GET'){requireUser(req,true);const f=db.prepare('SELECT * FROM lead_files WHERE id=?').get(parts[3]);if(!f)fail('Файл не найден',404);return serveFile(res,req,resolve(dataDir,'private',f.path),f.mime,f.name);}
 if(resource==='audit'&&method==='GET'){requireUser(req,true);return reply(res,200,db.prepare('SELECT actor,action,entity_id,created_at FROM audit_log ORDER BY id DESC LIMIT 300').all());}
 if(resource==='users'){requireUser(req,true);if(method==='GET')return reply(res,200,db.prepare('SELECT id,email,name,role,active,created_at FROM users ORDER BY created_at').all());if(['POST','PUT'].includes(method)){const data=await json(req),email=text(data.email,200).toLowerCase(),name=text(data.name,100),role=data.role,uid=parts[3]||id();if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['admin','editor'].includes(role))fail('Проверьте имя, email и роль');if(uid===u.id&&(data.active===false||role!=='admin'))fail('Нельзя отключить собственную административную учётную запись');const old=db.prepare('SELECT * FROM users WHERE id=?').get(uid);if(!old&&!data.password)fail('Задайте пароль');if(data.password&&data.password.length<14)fail('Пароль должен содержать не менее 14 символов');const password=data.password?await hashPassword(data.password):old.password;try{if(old)db.prepare('UPDATE users SET email=?,name=?,role=?,active=?,password=? WHERE id=?').run(email,name,role,data.active===false?0:1,password,uid);else db.prepare('INSERT INTO users(id,email,name,role,password,created_at) VALUES(?,?,?,?,?,?)').run(uid,email,name,role,password,now());}catch{fail('Email уже используется',409);}if(old)db.prepare('DELETE FROM sessions WHERE user_id=?').run(uid);audit(u,'Изменён пользователь: '+name,uid);return reply(res,200,{ok:true});}}
 fail('Маршрут не найден',404);}
 if(path==='/admin'||path==='/admin/')return reply(res,200,renderAdmin());
 if(path==='/admin/preview'){const u=requireUser(req);let item;const token=url.searchParams.get('token');if(token){const row=db.prepare('SELECT * FROM previews WHERE id=? AND user_id=? AND expires_at>?').get(token,u.id,Date.now());item=row?JSON.parse(row.data):null;}else item=unpack(db.prepare('SELECT * FROM content WHERE id=?').get(url.searchParams.get('id')));if(!item)fail('Предпросмотр не найден или истёк',404);return reply(res,200,renderPage('/'+sections[item.kind].route+'/'+item.slug,settings(),{preview:item}));}
 if(path==='/robots.txt')return reply(res,200,`User-agent: *\nDisallow: /admin\nDisallow: /api/\nSitemap: ${origin()}/sitemap.xml`,{'Content-Type':'text/plain'});
 if(path==='/sitemap.xml'){const links=['/','/company','/capabilities','/projects','/news','/suppliers','/contacts'];for(const[k,c]of Object.entries(sections)){if(!c.route)continue;const rows=list(k);if(rows.length)links.push('/'+c.route,...rows.map(x=>'/'+c.route+'/'+x.slug));}return reply(res,200,'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+links.map(x=>'<url><loc>'+origin()+x+'</loc></url>').join('')+'</urlset>',{'Content-Type':'application/xml'});}
 if(path.startsWith('/media/')){const name=path.slice(7);if(!/^[a-f0-9-]+(?:-\d+)?\.[a-z0-9]+$/.test(name))fail('Файл не найден',404);const row=db.prepare('SELECT * FROM media WHERE archived=0 AND (path=? OR variants LIKE ?)').get(name,'%/media/'+name+'%');if(!row)fail('Файл не найден',404);return serveFile(res,req,resolve(dataDir,'media',name),mimeFor(name),mimeFor(name).startsWith('application/')?row.name:undefined);}
 if(path.startsWith('/assets/')||['/app.js','/logo.js','/experience.css','/architecture.css','/architecture.js','/admin.js','/admin.css'].includes(path)){const file=resolve(publicDir,'.'+path);if(!file.startsWith(publicDir+sep))fail('Файл не найден',404);return serveFile(res,req,file,mime[extname(file)]||'application/octet-stream');}
 if(method!=='GET'&&method!=='HEAD')fail('Метод не поддерживается',405);const html=renderPage(path.replace(/\/$/,'')||'/',settings());if(!html)return reply(res,404,notFound(settings()));return reply(res,200,html);
 }catch(e){if(res.headersSent){res.end();return;}const status=e.status||500;if(status===500)console.error(e);reply(res,status,{error:status===500?'Не удалось выполнить действие. Попробуйте позже.':e.message});}}
export function start(port=Number(process.env.PORT||8788),host=process.env.HOST||'127.0.0.1'){if(process.env.NODE_ENV==='production'&&!origin().startsWith('https:'))throw Error('В production задайте APP_ORIGIN с HTTPS');const server=http.createServer(handler);server.requestTimeout=30000;server.headersTimeout=15000;server.listen(port,host,()=>console.log(`ССТ: ${origin()} (port ${server.address().port})`));const timer=setInterval(()=>deliverNotifications().catch(console.error),60000);timer.unref();server.on('close',()=>clearInterval(timer));return server;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href)start();
